---
- name: Delete routers
  hosts: "{{ variable_hosts }}"
  tags: delete_nodes
  gather_facts: no
  vars_files: 
    - group_vars/vmware
    - "files/{{ variable_hosts }}_nodes.yml"
  tasks:
  - name: delete vcp and vfpc
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
#      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: False
      name: "{{ item }}"
      folder: /
      datastore: "host 2 - datastore 2"
      state: absent
      force: yes
    loop:
    - "{{ inventory_hostname }}-vcp"
    - "{{ inventory_hostname }}-vfpc"
    delegate_to: localhost

- name: Delete internode vswitches
  hosts: "{{ variable_hosts }}"
  tags: delete_node_switches
  gather_facts: no
  vars_files: 
    - group_vars/vmware
    - "files/{{ variable_hosts }}_nodes.yml"
  tasks:
  - name: Delete the vswitch
    vmware_vswitch:
      hostname: "{{ esxi_hostname }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: False
      switch_name: "{{ item }}"
      state: absent
    loop: "{{ nodes[inventory_hostname]['switches'] }}"
    delegate_to: localhost

- name: Delete node bridge vswitches
  hosts: "{{ variable_hosts }}"
  tags: delete_bridge_switches
  gather_facts: no
  vars_files: 
    - group_vars/vmware
    - "files/{{ variable_hosts }}_nodes.yml"
  tasks:
  - name: Delete the vswitch
    vmware_vswitch:
      hostname: "{{ esxi_hostname }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: False
      switch_name: "{{ inventory_hostname }}-br-int"
      state: absent
    delegate_to: localhost
