---
- name: Push TI-LFA SR configs
  hosts: "{{ variable_hosts }}"
  roles:
  - juniper.junos
  gather_facts: no
  tasks:
  - name: Merge config
    juniper_junos_config:
      config_mode: "private"
      load: "replace"
      format: "text"
      timeout: 60
      commit: true
      diff: true
      src: templates/sr-tilfa.conf
      host: "{{ ansible_host }}"
      ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
    delegate_to: localhost
